name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    # Free GitHub Actions Environment Disk Space
    # Since runPluginVerifier task requires a lot of disk space for downloading IDEs,
    # without this, the build will fail due to disk full.
    - name: Maximize Build Space
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        large-packages: false
    - uses: actions/checkout@v2
    - name: Setup java
      uses: actions/setup-java@v1
      with:
         java-version: 17
    - name: Prepare for test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: listProductsReleases
    - name: Execute test
      uses: gradle/gradle-build-action@v2
      with:
        arguments: check
    - name: Setup Plugin Verifier IDEs Cache
      uses: actions/cache@v2.1.7
      with:
        path: ~/.pluginVerifier/ides
        key: plugin-verifier-${{ hashFiles('build/listProductsReleases.txt') }}
    - name: Run Plugin Verification tasks
      uses: gradle/gradle-build-action@v2
      with:
        arguments: runPluginVerifier -Pplugin.verifier.home.dir=~/.pluginVerifier/ides
